// const prompt=require('prompt-sync')();
// let a= prompt("what is yout name");
// let b= prompt("what is yout ");
// let c= prompt("what is yout fav colour");
// console.log(a+b+c); sync pro

//as
// console.log("start");
// setTimeout(function(){
//     console.log("i am good")
// },3000)0
// console.log("end");

//callbascks
// function loadscript(url,callback){
//     var script= document.createElement('script');
//     script.src=src;
//     document.body.appendChild(script);
// }
// loadscript("https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.js")
const greet= () =>{
    console.log("Hello world");
}
greet()